// <auto-generated>
//     Generated by website/tools/generate-gm-commands.py from the OpenMU server source.
//     DO NOT EDIT BY HAND - re-run the generator after pulling upstream.
//
//     The website has no ProjectReference into ../src (CI fails the build if one appears),
//     so this catalogue cannot be reflected at runtime the way OpenMU's own admin panel
//     does. It is generated and committed instead.
// </auto-generated>

namespace MuSite.Game;

/// <content>The generated command catalogue.</content>
public static partial class GmCommands
{
    /// <summary>Every chat command OpenMU ships, newest generation.</summary>
    public static readonly IReadOnlyList<GmCommand> All =
    [
        new("/add", GmStatus.Normal, false, "Handles the chat command '/add (ene|agi|vit|str|cmd) (amount)'. Adds the specified amount of stat points to the specified attribute of the character.", [new("StatType", "", GmArgKind.Text, false, false, ["str", "agi", "vit", "ene", "cmd"]), new("Amount", "", GmArgKind.Integer, false, false, [])]),
        new("/addagi", GmStatus.Normal, true, "Adds the specified amount of agility points to the character.", [new("Amount", "", GmArgKind.Integer, false, false, [])]),
        new("/addcmd", GmStatus.Normal, true, "Adds the specified amount of command points to the character.", [new("Amount", "", GmArgKind.Integer, false, false, [])]),
        new("/addene", GmStatus.Normal, true, "Adds the specified amount of energy points to the character.", [new("Amount", "", GmArgKind.Integer, false, false, [])]),
        new("/addstr", GmStatus.Normal, true, "Adds the specified amount of strength points to the character.", [new("Amount", "", GmArgKind.Integer, false, false, [])]),
        new("/addvit", GmStatus.Normal, true, "Adds the specified amount of vitality points to the character.", [new("Amount", "", GmArgKind.Integer, false, false, [])]),
        new("/banacc", GmStatus.GameMaster, false, "Handles the chat command '/banacc <acc>'. Bans an account from the game.", [new("AccountName", "acc", GmArgKind.Text, true, true, [])]),
        new("/banchar", GmStatus.GameMaster, false, "Handles the chat command '/banchar <char>'. Bans the account of a character from the game.", [new("CharacterName", "char", GmArgKind.Text, true, true, [])]),
        new("/battlesoccer", GmStatus.Normal, false, "Handles the chat command '/battlesoccer <guildname>'. Sends a request to the guild master of the requested guild.", [new("GuildName", "guildname", GmArgKind.Text, true, true, [])]),
        new("/charinfo", GmStatus.GameMaster, false, "Handles the chat command '/charinfo <char>'. Returns information about the character back to the requester.", [new("CharacterName", "char", GmArgKind.Text, true, true, [])]),
        new("/chatban", GmStatus.GameMaster, false, "Handles the chat command '/chatban <characterName> <durationMinutes>'. Bans the account of a character from chatting for the specified minutes.", [new("CharacterName", "characterName", GmArgKind.Text, true, true, []), new("DurationMinutes", "durationMinutes", GmArgKind.Integer, true, true, [])]),
        new("/chatunban", GmStatus.GameMaster, false, "Handles the chat command '/chatunban <characterName>'. Unbans the account of a character from chatting.", [new("CharacterName", "characterName", GmArgKind.Text, true, true, [])]),
        new("/clearinv", GmStatus.Normal, true, "Clears inventory. Usage: /clearinv (optional:character)", [new("CharacterName", "", GmArgKind.Text, false, false, [])]),
        new("/createmonster", GmStatus.GameMaster, false, "Handles the chat command '/createmonster <number> <intelligent>'. Creates a monster which can be remote controlled by the GM.", [new("MonsterNumber", "number", GmArgKind.Integer, true, true, []), new("IsIntelligent", "intelligence", GmArgKind.Flag, true, false, [])]),
        new("/disconnect", GmStatus.GameMaster, false, "Handles the chat command '/disconnect <char>'. Disconnects a player from the game server.", [new("CharacterName", "char", GmArgKind.Text, true, true, [])]),
        new("/fireworks", GmStatus.GameMaster, false, "Handles the chat command '/fireworks <x> <y>'. Shows an fireworks effect at the specified coordinates.", [new("X", "x", GmArgKind.Integer, true, true, []), new("Y", "y", GmArgKind.Integer, true, true, [])]),
        new("/get", GmStatus.GameMaster, true, "Get stat points. Usage: /get (ene|agi|vit|str|cmd) (optional:character)", [new("StatType", "", GmArgKind.Text, false, false, ["str", "agi", "vit", "ene", "cmd"]), new("CharacterName", "", GmArgKind.Text, false, false, [])]),
        new("/getlevel", GmStatus.GameMaster, true, "Gets level of a player. Usage: /getlevel (optional:character)", [new("CharacterName", "", GmArgKind.Text, false, false, [])]),
        new("/getleveluppoints", GmStatus.GameMaster, true, "Gets level up points of a player. Usage: /getleveluppoints (optional:character)", [new("CharacterName", "", GmArgKind.Text, false, false, [])]),
        new("/getmasterlevel", GmStatus.GameMaster, true, "Gets master level of a player. Usage: /getmasterlevel (optional:character)", [new("CharacterName", "", GmArgKind.Text, false, false, [])]),
        new("/getmasterleveluppoints", GmStatus.GameMaster, true, "Gets master level up points of a player. Usage: /getmasterleveluppoints (optional:character)", [new("CharacterName", "", GmArgKind.Text, false, false, [])]),
        new("/getmoney", GmStatus.GameMaster, true, "Gets money of a player. Usage: /getmoney (optional:character)", [new("CharacterName", "", GmArgKind.Text, false, false, [])]),
        new("/getresets", GmStatus.GameMaster, true, "Gets resets of a player. Usage: /getresets (optional:character)", [new("CharacterName", "", GmArgKind.Text, false, false, [])]),
        new("/guilddisconnect", GmStatus.GameMaster, false, "Handles the chat command '/guilddisconnect <guild>'. Disconnect the guild members.", [new("GuildName", "guild", GmArgKind.Text, true, true, [])]),
        new("/guildmove", GmStatus.GameMaster, false, "Handles the chat command '/guildmove <guild> <map> <x?> <y?>'. Move the character from a guild to a specified map and coordinates.", [new("GuildName", "guild", GmArgKind.Text, true, true, []), new("MapIdOrName", "mapIdOrName", GmArgKind.Text, true, true, []), new("X", "x", GmArgKind.Integer, true, false, []), new("Y", "y", GmArgKind.Integer, true, false, [])]),
        new("/help", GmStatus.Normal, false, "Handles the /help <command> chat command. Shows information about the requested command.", []),
        new("/hide", GmStatus.GameMaster, false, "Handles the chat command '/hide'. Hides the own player from others.", []),
        new("/item", GmStatus.GameMaster, false, "Handles the chat command '/item <group> <number> <lvl?> <exc?> <sk?> <lu?> <opt?> <anc?> <ancBonuslvl?>'. Drops a specific item next to the character.", [new("Group", "group", GmArgKind.Integer, true, true, []), new("Number", "number", GmArgKind.Integer, true, true, []), new("Level", "lvl", GmArgKind.Integer, true, false, []), new("ExcellentNumber", "ex", GmArgKind.Integer, true, false, []), new("Skill", "sk", GmArgKind.Flag, true, false, []), new("Luck", "lu", GmArgKind.Flag, true, false, []), new("Opt", "opt", GmArgKind.Integer, true, false, []), new("Ancient", "anc", GmArgKind.Integer, true, false, ["0", "1", "2"]), new("AncientBonusLevel", "ancBonuslvl", GmArgKind.Integer, true, false, ["1", "2"])]),
        new("/language", GmStatus.Normal, false, "Handles the chat command '/language <isoCode>'. Changes the language of the account.", [new("IsoLanguageCode", "isoCode", GmArgKind.Text, true, true, [])]),
        new("/list", GmStatus.Normal, false, "Lists all the commands.", []),
        new("/move", GmStatus.Normal, false, "Handles the chat command '/move <target> <mapIdOrName?> <x?> <y?>'. Moves the character to the specified destination.", [new("Target", "target", GmArgKind.Text, true, true, []), new("MapIdOrName", "mapIdOrName", GmArgKind.Text, true, false, []), new("X", "x", GmArgKind.Integer, true, false, []), new("Y", "y", GmArgKind.Integer, true, false, [])]),
        new("/movemonster", GmStatus.GameMaster, false, "Handles the chat command '/movemonster <id> <x> <y>'. Moves a previously created monster which can be remote controlled by the GM.", []),
        new("/npc", GmStatus.Normal, true, "Opens the merchant NPC store.", [new("NpcId", "", GmArgKind.Text, false, false, [])]),
        new("/offlevel", GmStatus.Normal, false, "Allows players to start offline leveling with /offlevel. The character stays in the world after the client disconnects and stops when the player logs back in.", []),
        new("/online", GmStatus.GameMaster, false, "Handles the chat command '/online'. Gets the count of game masters and players online.", []),
        new("/openware", GmStatus.Normal, true, "Opens the warehouse.", []),
        new("/pk", GmStatus.GameMaster, false, "", [new("CharacterName", "char", GmArgKind.Text, true, true, []), new("Level", "pk_lvl", GmArgKind.Integer, true, true, ["1", "2", "3"]), new("Count", "pk_count", GmArgKind.Integer, true, true, [])]),
        new("/pkclear", GmStatus.Normal, false, "", [new("CharacterName", "char", GmArgKind.Text, true, false, [])]),
        new("/removenpc", GmStatus.GameMaster, false, "Handles the chat command '/removenpc <id>'.", [new("Id", "id", GmArgKind.Integer, true, true, [])]),
        new("/reset", GmStatus.Normal, false, "Handles the chat command '/reset'.", []),
        new("/resetinfo", GmStatus.Normal, false, "Handles the chat command '/resetinfo'. Shows the required costs and the granted points for the next reset.", []),
        new("/resetstats", GmStatus.Normal, false, "Handles the chat command '/resetstats'.", []),
        new("/set", GmStatus.GameMaster, true, "Set stat points. Usage: /set (ene|agi|vit|str|cmd) (amount) (optional:character)", [new("StatType", "", GmArgKind.Text, false, false, ["str", "agi", "vit", "ene", "cmd"]), new("Amount", "", GmArgKind.Integer, false, false, []), new("CharacterName", "", GmArgKind.Text, false, false, [])]),
        new("/setlevel", GmStatus.GameMaster, true, "Sets level of a player. Usage: /setlevel (level) (optional:character)", [new("Level", "", GmArgKind.Integer, false, false, []), new("CharacterName", "", GmArgKind.Text, false, false, [])]),
        new("/setleveluppoints", GmStatus.GameMaster, true, "Sets level up points of a player. Usage: /setleveluppoints (points) (optional:character)", [new("LevelUpPoints", "", GmArgKind.Integer, false, false, []), new("CharacterName", "", GmArgKind.Text, false, false, [])]),
        new("/setmasterlevel", GmStatus.GameMaster, true, "Sets master level of a player. Usage: /setmasterlevel (level) (optional:character)", [new("MasterLevel", "", GmArgKind.Integer, false, false, []), new("CharacterName", "", GmArgKind.Text, false, false, [])]),
        new("/setmasterleveluppoints", GmStatus.GameMaster, true, "Sets master level up points of a player. Usage: /setmasterleveluppoints (points) (optional:character)", [new("MasterLevelUpPoints", "", GmArgKind.Integer, false, false, []), new("CharacterName", "", GmArgKind.Text, false, false, [])]),
        new("/setmoney", GmStatus.GameMaster, true, "Sets money of a player. Usage: /setmoney (amount) (optional:character)", [new("Amount", "", GmArgKind.Integer, false, false, []), new("CharacterName", "", GmArgKind.Text, false, false, [])]),
        new("/setresets", GmStatus.GameMaster, true, "Sets resets of a player. Usage: /setresets (resets) (optional:character)", [new("Resets", "", GmArgKind.Integer, false, false, []), new("CharacterName", "", GmArgKind.Text, false, false, [])]),
        new("/showids", GmStatus.GameMaster, false, "", []),
        new("/skin", GmStatus.GameMaster, false, "Handles the chat command '/skin <number>'. Applies a monster skin to the game masters character.", [new("SkinNumber", "skin", GmArgKind.Integer, true, true, [])]),
        new("/startbc", GmStatus.GameMaster, false, "Handles the chat command '/startbc'. Starts the blood castle event at the next possible time.", []),
        new("/startcc", GmStatus.GameMaster, false, "Handles the chat command '/startcc'. Starts the chaos castle event at the next possible time.", []),
        new("/startds", GmStatus.GameMaster, false, "Handles the chat command '/startds'. Starts the devil square event at the next possible time.", []),
        new("/teleport", GmStatus.GameMaster, false, "Handles the chat command '/teleport <x> <y>'. Teleports the game master to the specified coordinates.", [new("X", "x", GmArgKind.Integer, true, true, []), new("Y", "y", GmArgKind.Integer, true, true, [])]),
        new("/trace", GmStatus.GameMaster, false, "Handles the chat command '/trace <char>'. Moves the game master to the character's location.", [new("CharacterName", "char", GmArgKind.Text, true, true, [])]),
        new("/track", GmStatus.GameMaster, false, "Handles the chat command '/track <char>'. Moves the player to the game masters location.", [new("CharacterName", "char", GmArgKind.Text, true, true, [])]),
        new("/unbanacc", GmStatus.GameMaster, false, "Handles the chat command '/unbanacc <acc>'. Unbans an account from the game.", [new("AccountName", "acc", GmArgKind.Text, true, true, [])]),
        new("/unbanchar", GmStatus.GameMaster, false, "Handles the chat command '/unbanchar <char>'. Unbans the account of a character from the game.", [new("CharacterName", "char", GmArgKind.Text, true, true, [])]),
        new("/unhide", GmStatus.GameMaster, false, "Handles the chat command '/unhide'. Unhides the own player from others.", []),
        new("/walkmonster", GmStatus.GameMaster, false, "Handles the chat command '/walkmonster <id> <x> <y>'. Walks a previously created monster which can be remote controlled by the GM.", []),
        new("/war", GmStatus.Normal, false, "Handles the chat command '/war <guild>'. Sends a request to the guild master of the requested guild.", [new("GuildName", "guildname", GmArgKind.Text, true, true, [])]),
        new("/xmasfireworks", GmStatus.GameMaster, false, "Handles the chat command '/xmasfireworks <x> <y>'. Shows an christmas fireworks effect at the specified coordinates.", [new("X", "x", GmArgKind.Integer, true, true, []), new("Y", "y", GmArgKind.Integer, true, true, [])]),
    ];
}
